# Generated by Django 2.2.3 on 2020-01-29 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoopTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=20)),
                ('isDelete', models.NullBooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CoopUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.NullBooleanField(default=1)),
                ('school', models.CharField(default='', max_length=50)),
                ('hobby', models.CharField(blank=True, max_length=200)),
                ('qqNum', models.CharField(blank=True, default='', max_length=10)),
                ('phone', models.CharField(max_length=11)),
                ('profession', models.CharField(max_length=50)),
                ('createTime', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoopPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postTitle', models.CharField(max_length=100)),
                ('postWish', models.NullBooleanField()),
                ('postContent', models.CharField(max_length=300)),
                ('postCreateTime', models.DateField(auto_now_add=True)),
                ('isDelete', models.NullBooleanField(default=False)),
                ('postMaster', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coopuser.CoopUserInfo')),
                ('postTag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coopuser.CoopTag')),
            ],
        ),
        migrations.CreateModel(
            name='CoopComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentContent', models.CharField(max_length=200)),
                ('commentCreateTime', models.DateTimeField(auto_now_add=True)),
                ('isDelete', models.NullBooleanField(default=False)),
                ('commentPost', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coopuser.CoopPost')),
                ('commentUp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coopuser.CoopComment')),
                ('commentUser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coopuser.CoopUserInfo')),
            ],
        ),
    ]
