# Generated by Django 2.2.3 on 2020-02-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coopuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopcomment',
            name='commentUp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coopuser.CoopComment'),
        ),
    ]
